# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2019 Brett Sheffield <brett@gladserv.com>

.PHONY:		install

install:
		install -d $(PREFIX)/share/man/man1
		install *.1 $(PREFIX)/share/man/man1/
