.TH MLDSPY 1 "22 August 2019" "v0.0.1" "User Commands"
.SH NAME
mldspy \- multicast listener discovery watcher
.SH SYNOPSIS
.EX
\fBmldspy\fP [options]
.EE
.SH DESCRIPTION
Watch Multicast Listener Discovery (MLDv2) messages on the wire.
.SH OPTIONS
.TP 0.5i
.B \-\-debug 
Increase logging level.
.TP 0.5i
.B \-\-noexpire 
Don't expire group or source records from cache.
.PP
.SH BUGS
Wot?  Where?  Oh, it does *that*...  Ok.  Sure.
.PP
https://github.com/brettsheffield/mldspy/issues
.PP
.SH COPYRIGHT
Copyright (c) 2019 Brett A C Sheffield <brett@gladserv.com>
.LP
All rights reserved.
.LP
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.LP
See file COPYING for full license details.
